### ISSUE TITLE
Mod Suggestions for TNP Limitless 6

### ISSUE THREAD

**Issue by Gbergz** [The-Nexus-Project/Limitless-6#1]
# Suggestions have moved!

---

### Got any suggestions?
Leave them in our discord channel under #mod-suggestions.

----

## Discord Invite: https://discord.gg/gwzpyQb

**Comment by ShawnKilbride** [comment]
In protest of the new chat reporting "feature", the developer of enigmatic legacy made this: https://www.curseforge.com/minecraft/mc-mods/no-chat-reports

**Comment by Traincrafter111** [comment]
I think the Mahou Tsukai Mod would be a nice addition, as it is one of the best magic mods right now
https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai

**Comment by Xplodin** [comment]
> In protest of the new chat reporting "feature", the developer of enigmatic legacy made this: https://www.curseforge.com/minecraft/mc-mods/no-chat-reports

100% needed

**Comment by Gbergz** [comment]
@Xplodin Already in the pack...

**Comment by FleetAdmiralJakob** [comment]
[Upgraded Netherite: Items](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-items)
![image](https://user-images.githubusercontent.com/77451351/177276047-01260cb2-d456-4d3f-839b-aa980c638197.png)

**Comment by FleetAdmiralJakob** [comment]
[Upgraded Tools](https://www.curseforge.com/minecraft/mc-mods/upgraded-tools)
![image](https://user-images.githubusercontent.com/77451351/177276449-a33e564c-ee88-4018-8cfc-cc6303e03795.png)

**Comment by FleetAdmiralJakob** [comment]
[Upgraded Netherite : Ultimerite](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-ultimerite)

[Upgraded Netherite : Creativerite](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-creativerite)

![image](https://user-images.githubusercontent.com/77451351/177276705-ee18038f-7d5a-48d6-9c98-662ff3b23fc4.png)

![image](https://user-images.githubusercontent.com/77451351/177276755-4af382d5-95fa-4ff4-9343-506f5dd2cb1c.png)

**Comment by FleetAdmiralJakob** [comment]
[Fast Leaf Decay](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)

**Comment by FleetAdmiralJakob** [comment]
**Food Update**

[The Veggie Way](https://www.curseforge.com/minecraft/mc-mods/veggieway-fabric)

[Spice of Life: Carrot Edition](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition)

**Comment by FleetAdmiralJakob** [comment]
> @Xplodin Already in the pack...

Mahou Tsukai is not in TNP Limitless 6. I hope you add it.

**Comment by Egaliterrier** [comment]
Maybe some performance mods, like rubidium, krypton, radon, radium or starlight?

**Comment by Gbergz** [comment]
@Egaliterrier Probably not as they break too many mods right now.

**Comment by Xplodin** [comment]
> @Xplodin Already in the pack...

good stuff  my guy. That chat report is beyond a broken function.
My buddy got banned just by playing 1.19 without it once. All due to false reports

**Comment by Duckos-Mods** [comment]
Add cc:tweaked

**Comment by Gbergz** [comment]
@Duckos-Mods Will do eventually when it doesn't crash.

**Comment by ValryonOmega** [comment]
@Duckos-Mods Yes but it crashes servers, I tried to manually add it and it crashes the server, Even tried a fresh server with no other mods and it still crashes.

**Comment by MKALJANABY** [comment]
https://www.curseforge.com/minecraft/mc-mods/solargeneration solar panels!
https://www.curseforge.com/minecraft/mc-mods/orelibrary requirement for solar generation
https://www.curseforge.com/minecraft/mc-mods/planttech-2/files this mod seems pretty large and i don't think you have experience with it before so maybe test it a bit?
https://www.curseforge.com/minecraft/mc-mods/plant-in-a-jar this would fit with the easyvillagers and easypiglins but it might be too easy...?
https://www.curseforge.com/minecraft/mc-mods/portable-mobs this one i just found interesting but i feel like it's either gonna be op or useless

**Comment by Evilteen18** [comment]
i seen these 2 mods beer mod https://www.curseforge.com/minecraft/mc-mods/alcocraft-beer-and-stuff and
pizza mod https://www.curseforge.com/minecraft/mc-mods/pizzacraft i just like the idea of these mods but if you dont want to or cant im ok i just want to help is all ^ ^

**Comment by ShadowMagnus000** [comment]
Tech mod since the main tech mods are still not available on 1.19 https://www.curseforge.com/minecraft/mc-mods/assemblylinemachines

**Comment by NiceClown** [comment]
Meka https://www.curseforge.com/minecraft/mc-mods/mekanism

**Comment by IlBardoMassese** [comment]
AoA one of the biggest exploration/Rpg mod ever created
https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine/files/3884642

**Comment by Xplodin** [comment]
> AoA one of the biggest exploration/Rpg mod ever created https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine/files/3884642

aoa for 1.18.2 doesnt have dimensions added yet still I believe

**Comment by NiceClown** [comment]
> > Meka https://www.curseforge.com/minecraft/mc-mods/mekanism
> 
> @NiceClown This will ofcourse be added sometime in the future, but it's currently hard to create a modpack for the newest forge version right now due to breaking forge changes and mods not being updated for it.
> 
> 1.19.1 is looking more likely right now. Once mekanism is out for it ofcourse, and once 1.19.1 is actually out.

ok, thx!)

**Comment by IlBardoMassese** [comment]
> > AoA one of the biggest exploration/Rpg mod ever created https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine/files/3884642
> 
> aoa for 1.18.2 doesnt have dimensions added yet still I believe

idk, the mods in 1.16 and in 1.19 are the same size, i can hypotize that there are the same things

**Comment by JaisDK** [comment]
https://www.curseforge.com/minecraft/mc-mods/golemsarefriends

**Comment by cooltom542** [comment]
i will love if you add this mod mahou taskai here is the link if you add it

https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai

**Comment by ArchieBeepBoop** [comment]
Consider checking:

Pluto (A network handler and package consolidation optimizer that works wonders in reducing cpu usage for multiplayer)
https://www.curseforge.com/minecraft/mc-mods/pluto

Rubidium (No longer seems to break mods that use niche rendering pipelines, like create)
https://www.curseforge.com/minecraft/mc-mods/rubidium

**Comment by Griffidl** [comment]
https://www.curseforge.com/minecraft/mc-mods/projecte

Always a fun edition

**Comment by Griffidl** [comment]
https://www.curseforge.com/minecraft/mc-mods/scaling-health

Allows for difficulty scaling to keep some challenge as players advance to later gear. Especially with Apotheosis affix.

**Comment by t-lum** [comment]
Some Addons of Create that are now in 1.19.2

Create : Misc & Things
https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things

Create: Extended Flywheels
https://www.curseforge.com/minecraft/mc-mods/create-extended-flywheels

Create Confectionery
https://www.curseforge.com/minecraft/mc-mods/create-confectionery

Create Enchantment Industry
https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry

**Comment by haha26315** [comment]
Unsure if you handle balancing / tweaks in individual modpacks rather than just compiling the mods wholesale into the pack, but if so, here's my suggestion.
Buff the input / output rate of Dynamic Tanks from Mekanism so they can be used as a gas buffer for reactors. Currently I believe they only match the rate of Ultimate chemical tanks which is disappointing when they're a multiblock, in my opinion.

**Comment by newtrogicNexus** [comment]
[Ad Astra](https://www.curseforge.com/minecraft/mc-mods/ad-astra) to replace Beyond Earth.

**Comment by CrimsonXMC** [comment]
[Chance Cubes](https://www.curseforge.com/minecraft/mc-mods/chance-cubes) cause i like my base going boom

**Comment by SkiaLunar** [comment]
One of my friends recommended [MineColonies](https://www.curseforge.com/minecraft/mc-mods/minecolonies) if that fits with your plans for the pack.  Thanks for the time to read this message, the pack is wonderful with my friends.

**Comment by TachUDF** [comment]
Relics (now available for 1.19.2) https://www.curseforge.com/minecraft/mc-mods/relics-mod

**Comment by ParsaPilehvari** [comment]
> One of my friends recommended [MineColonies](https://www.curseforge.com/minecraft/mc-mods/minecolonies) if that fits with your plans for the pack. Thanks for the time to read this message, the pack is wonderful with my friends.

I second this suggestion, I think it would be a good fit for TNP6 as an advancement chapter as well.

**Comment by DewDrop-99** [comment]
[Serene Seasons ](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)

**Comment by newtrogicNexus** [comment]
[Better Grinder](https://www.curseforge.com/minecraft/mc-mods/better-grinder) to replace PlainGrinder

**Comment by FloofiestAzezn** [comment]
We have lots of pets/tames.. Why not give em some love with: https://www.curseforge.com/minecraft/mc-mods/domestication-innovation ! Made by Alex's mobs dev so you KNOW it's good x3

**Comment by CarlosMZ12268** [comment]
One mod I think would be really useful is corail recycler: https://www.curseforge.com/minecraft/mc-mods/corail-recycler. It's very useful for getting rid of unnecessary junk in the early game while still getting back materials.

**Comment by EBRPyle** [comment]
While it isnt implemented for 1.19, or even fully for 1.16, nuclearcraft would be outstanding in this pack. Nuclearcraft has got to be my favorite mod, hopefully they will get it updated sooner than later

**Comment by MiriamAlter** [comment]
AE2 Wireless Terminals https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals
More wireless terminal options PLUS ability to curio slot them.

**Comment by Tezu-SilverMoon** [comment]
would u add "https://www.curseforge.com/minecraft/mc-mods/daves-building-extended" it lets u customize the trains of create better, "https://www.curseforge.com/minecraft/mc-mods/create-extended-flywheels" this adds flywheels that rotate also for the trains of create

and only if its possible to add https://www.curseforge.com/minecraft/mc-mods/minecolonies i think its self explanatory what Minecolonies is

thanks

**Comment by RConTRS** [comment]
wall jump please, can't go without it at somepoint https://www.curseforge.com/minecraft/mc-mods/wall-jump

**Comment by RConTRS** [comment]
also, noticed that tnp 6 and 5 has some missing mods like fast leaf decay https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay and carryon https://www.curseforge.com/minecraft/mc-mods/carry-on also faster ladder climbing, it's outdated but thankfully an alternative exist https://www.curseforge.com/minecraft/mc-mods/climb-ladders-fast

**Comment by Gbergz** [comment]
@RConTRS It already has Fast Leaf Decay (but its named something else), also has Faster Ladder climbing, another name again though. And Carry On won't be added due to frequent crashing issues when picking up certain blocks, entities / tile entities.

**Comment by RConTRS** [comment]
aight

**Comment by BoosterBoose** [comment]
https://www.curseforge.com/minecraft/mc-mods/ic2-classic   
for 1.19.2

**Comment by Evilteen18** [comment]
i think this will be a fun mod to have https://www.curseforge.com/minecraft/mc-mods/parcool

**Comment by Bit-Flare** [comment]
This is less of a mod suggestion and more of a balance suggestion, but it'd be nice if the ore processing ratios were changed. 

At the moment you can double raw ore with the plain grinder, which is better or as good ratio as all of the other early game or processing options (for example thermal expansion gets about a 1.6x multiplication of ore with base the induction smelter, while an Arc Furnace gets about a 1.5x multiplication, both machines being later in progression for both mods). The plain grinder is only beat when you reach the option of using a chemical injection chamber with mekanism or chaining the elemental craft ore purifier with the mekanism purification chamber. (Rough calculations [here](https://docs.google.com/spreadsheets/d/1-0AZPd09azhFWp3asZInLS_Fi6Qk14oZlNPA4b5BTTw/edit?usp=sharing))

I'd prefer the ratios of modded raw ore processing to be increased to pre-raw ore era levels, because in vanilla minecraft an ore block drops 1 raw ore if you don't have fortune making it equivalent to 1 ore = 1 raw ore, but really an incentive to use the modded machines over the more manual options would be nice.

Thanks for taking the time to look at this

**Comment by Bobkat01** [comment]
I personally would like to see this mod [https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers](url) for making botany pot mass production setups more compact.

**Comment by MommaBeeVR** [comment]
> I think the Mahou Tsukai Mod would be a nice addition, as it is one of the best magic mods right now https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai

sadly that's for 1.16.5.
Outdated.

**Comment by Xplodin** [comment]
> 

thats false.
Its for 1.16.5-1.19.3

**Comment by TheFieryFalcon** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/modernfix and https://legacy.curseforge.com/minecraft/mc-mods/lightspeedmod for performance

for content, maybe something like https://legacy.curseforge.com/minecraft/mc-mods/biomancy, https://legacy.curseforge.com/minecraft/mc-mods/solar-forge or https://legacy.curseforge.com/minecraft/mc-mods/assemblylinemachines?

**Comment by Deiwos** [comment]
Hi I'd like to suggest https://www.curseforge.com/minecraft/mc-mods/crafting-station
It works exactly the same as a TiCon Crafting Station but standalone.

**Comment by Reyshyram** [comment]
Maybe
[https://www.curseforge.com/minecraft/mc-mods/culllessleaves-reforged](https://www.curseforge.com/minecraft/mc-mods/culllessleaves-reforged), [https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities-reforged-unofficial](https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities-reforged-unofficial) and [https://modrinth.com/mod/seaborgium](https://modrinth.com/mod/seaborgium) for performance? (Haven’t tried them)

**Comment by Gbergz** [comment]
@Reyshyram The first two mods are actually already being tested. We'll see when I am done :)

**Comment by Reyshyram** [comment]
> @Reyshyram The first two mods are actually already being tested. We'll see when I am done :)

Okay 👍

**Comment by BarterChain65YT** [comment]
https://modrinth.com/mod/more-music-discs/version/1.19.2-22 it will add a few more music discs such as dog which is the other half of cat on legacy console edition

**Comment by Gbergz** [comment]
@Reyshyram Added the first two mods in your suggestions in last update. (v1.23.0)
(Cull Leaves & Enhanced Block Entities.)

**Comment by TachUDF** [comment]
Cloud Storage https://www.curseforge.com/minecraft/mc-mods/alexs-cloud-storage
Meet Your Fight https://www.curseforge.com/minecraft/mc-mods/meet-your-fight
Botanic Additions https://www.curseforge.com/minecraft/mc-mods/botanic-additions

**Comment by jamescastle** [comment]
Since there are a lot of books for the different mods, I'd suggest the Akashic Tome:
https://www.curseforge.com/minecraft/mc-mods/akashic-tome
(AutoRegLib needed https://www.curseforge.com/minecraft/mc-mods/autoreglib)

**Comment by lohkiii** [comment]
Hi, this is my first time using Github so pardon me if this is a dumb post here in this community.
I just started running an SMP with a bunch of people and so thought having a mod that allowed banners to be worn would be a cool idea.  This is what I found :)
https://www.curseforge.com/minecraft/mc-mods/more-banner-features/about
Thought it would be a cool little feature haha

**Comment by Glasspaw** [comment]
I would like to suggest the addition of Forbidden And Arcanus.
Thank you.

**Comment by Glasspaw** [comment]
https://www.curseforge.com/minecraft/mc-mods/argentinasdelight

And this one too, sorry for the two post

**Comment by Sorro123** [comment]
[Lightspeed](https://www.curseforge.com/minecraft/mc-mods/lightspeedmod)

**Comment by Gbergz** [comment]
@Sorro123 Already in the pack.

**Comment by Sorro123** [comment]
Sorry, I checked [Modpack Index](https://www.modpackindex.com/modpack/47314/tnp-limitless-6-ll6) but it didn't show up

**Comment by Sorro123** [comment]
How about [Sound Physics](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered), [Plasmo voice](https://www.curseforge.com/minecraft/mc-mods/plasmo-voice) (and its addons, [Sculk](https://modrinth.com/plugin/pv-addon-sculk) and [Soundphysics](https://modrinth.com/mod/pv-addon-soundphysics), [Presence Footsteps](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge), and [Essential](https://www.curseforge.com/minecraft/mc-mods/essential-mod)

**Comment by icha-senpai** [comment]
> 

![image](https://github.com/The-Nexus-Project/Limitless-6/assets/10746379/de27f7c3-f58c-4a44-b1b7-fcbb1680f668)
don't worry it definitely in the pack

**Comment by Schildos** [comment]
[ME Requester](https://www.curseforge.com/minecraft/mc-mods/merequester)
Yeah could do it the old fashioned way with export buses on an interface and level emitters, but this seems a lot less annoying to setup

**Comment by Fastdragon1107** [comment]
The mod [Minecolonies](https://www.curseforge.com/minecraft/mc-mods/minecolonies) would be a great addition.

**Comment by icha-senpai** [comment]
> The mod [Minecolonies](https://www.curseforge.com/minecraft/mc-mods/minecolonies) would be a great addition.

at that point go play ATM packs

**Comment by Xplodin** [comment]
> > The mod [Minecolonies](https://www.curseforge.com/minecraft/mc-mods/minecolonies) would be a great addition.
> 
> at that point go play ATM packs

you do realize TNP series has more than twice the mods than ATM packs right?

**Comment by Gbergz** [comment]
Please limit any conversations in this thread, thank you :)

**Comment by Griefed** [comment]
[Enhanced Celestials](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials)

> Adds lunar phases, such as a Harvest Moon and Blood Moon to spice up regular gameplay a little.

[Immersive Posts](https://www.curseforge.com/minecraft/mc-mods/immersiveposts)

> Adds some simple posts working well with Immersive Engineering both usability and decoration wise.

[Easier Sleeping](https://www.curseforge.com/minecraft/mc-mods/easier-sleeping)

> So only 50% of the players on a server need to be in bed to trigger night skip

[ProjectE](https://www.curseforge.com/minecraft/mc-mods/projecte)

> Useful to get rid of waste items (looking at you, 13242345 stacks of dirt and cobble) and turn it into useful stuff.

Already suggested by someone else: MineColonies

---

Thank you for putty so much time and effort into this pack! 😊

**Comment by ZEROOblivious** [comment]
https://www.curseforge.com/minecraft/mc-mods/feywild

Possibly FeyWild just to add more of that mystic aspect to the modpack. Would fit great with Botania and MythicBotany since Alfhiem Realm is a bit barren (own developers fault); but adding it in would just make botania area look pleasing.

**Comment by TheOceanBreeze** [comment]
https://www.curseforge.com/minecraft/mc-mods/dynamic-surrounding-resurrected

This would be a fun mod to add.

**Comment by TheOceanBreeze** [comment]
Also I would love to see some of the mods from the newer version of the modpack make it into this version if they are compatible.

**Comment by Gbergz** [comment]
# Suggestions have moved!

----

Leave them in our discord channel under #mod-suggestions.
## Discord Invite: https://discord.gg/gwzpyQb
