### ISSUE TITLE
Jetpack glitch[Issue]: 

### ISSUE THREAD

**Issue by JediAvenger** [The-Nexus-Project/Limitless-6#10]
### What happened?

A bug happened!  When I toggle a jetpack engine on or off, the game generates a large structure with a smooth stone floor & glass walls.  It is filled with machines & items.  It over writes the landscape and all but destroyed my base.  Playing single player with cheats on.

### Pack Version

Version: Just updated to 1.3.0 and it still has this glitch.

### To Reproduce

1.Toggle jetpack engine on or off.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

It was awesome fun playing this pack until I encountered this glitch.  Hopefully it will get fixed soon.  Thanks for all your hard work.

**Comment by Gbergz** [comment]
It's the debug mode from "Inventory Profiles Next" being enabled. Should be off but I guess it's not.

**Comment by Gbergz** [comment]
Thanks for report.

**Comment by Gbergz** [comment]
Uploaded v1.3.1 which turns it off.
