### ISSUE TITLE
[Issue]: Tempad portal is invisible when summoned

### ISSUE THREAD

**Issue by Xiarno** [The-Nexus-Project/Limitless-6#106]
### What happened?

The Tempad portal is invisible when summoned.

### Pack Version

Version: Limitless 6 - v1.27.0

### To Reproduce

1. Make a Tempad
2. Register a location on the Tempad.
3. Summon the portal to that location.

Noticed the portal is invisible.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [X] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

I mentioned using Oculus & none because I tried with shaders, without shaders & without Oculus installed. Both have the same results. The portal is invisible.

**Comment by Xiarno** [comment]
Updating the mod to Tempad 1.4.5 fixed the issue.
Closing.

**Comment by Gbergz** [comment]
That version will be included next modpack update.
