### ISSUE TITLE
[Issue]:  Game Crashes when placing the tesseract

### ISSUE THREAD

**Issue by DrCr4b1** [The-Nexus-Project/Limitless-6#108]
### What happened?

I placed the tesseract on our Server. It was just a unvisible block and it crashed the game almost instantly

### Pack Version

Version: TNP Limetless 6-1.19.0

### To Reproduce

1.Place a tesseract

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
logs, crash report. you missed the most important part of the report..

**Comment by DrCr4b1** [comment]
The Log and crash report when I tested it in singleplayer is attached aswell

[crash-2023-06-26_16.58.25-client.txt](https://github.com/The-Nexus-Project/Limitless-6/files/11896373/crash-2023-06-26_16.58.25-client.txt)
[crash-2023-06-26_17.06.07-client.txt](https://github.com/The-Nexus-Project/Limitless-6/files/11896374/crash-2023-06-26_17.06.07-client.txt)
[crash-2023-06-26_17.18.07-client.txt](https://github.com/The-Nexus-Project/Limitless-6/files/11896375/crash-2023-06-26_17.18.07-client.txt)
[2023-06-26-1.log.gz](https://github.com/The-Nexus-Project/Limitless-6/files/11896406/2023-06-26-1.log.gz)
[2023-06-26-2.log.gz](https://github.com/The-Nexus-Project/Limitless-6/files/11896407/2023-06-26-2.log.gz)
[2023-06-26-3.log.gz](https://github.com/The-Nexus-Project/Limitless-6/files/11896408/2023-06-26-3.log.gz)

**Comment by Gbergz** [comment]
it's the cause, and it's not in the modpack (anymore) so you either added it or are on an older version of the pack.

**Comment by Gbergz** [comment]
no worries
