### ISSUE TITLE
Numpad 4 causes debug mode to activate [Issue]: 

### ISSUE THREAD

**Issue by JediAvenger** [The-Nexus-Project/Limitless-6#11]
### What happened?

A bug happened!  The debug mode activates when numpad 4 or keypad 4 is pressed.  I had the jetpack engine bound to this key, so I thought is was a jetpack issue, but I was mistaken.  I changed the key binds, and the jetpack works fine.  But anytime you press numpad 4, it generates the debug area.  Playing single player with cheats on.

### Pack Version

Version: 1.3.1

### To Reproduce

1. Press numpad 4.
2. Generates debug area in game.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Firedale** [comment]
In addition to the reported issue; the keybind for it doesn't seem to be easily findable within the configs or when changing the keybinds from within the game, so there's no way to disable this that I can find.  There is nothing bound in my settings to Keypad 4, yet it still spawns a debug area.

**Comment by Gbergz** [comment]
Redownload 1.3.1, this is fixed.
