### ISSUE TITLE
[Issue]: Higher frame rate and higher component utilization when in debug screen or F1

### ISSUE THREAD

**Issue by Oleika009** [The-Nexus-Project/Limitless-6#110]
### What happened?

I just installed TNP Limitless 6 version 1.28.1 and noticed that I can barely get 50fps but get a lot more fps when hiding the gui with F1 or opening the debug screen with F3. My gpu and cpu sit at about 20% - 30% utilization but when I hide the gui or open the debug screen the gpu usage jumps to 60% or more and my fps reach above 100. I have 10048mb allocated to minecraft but I get the same result with 16128mb allocated. The shader used is the Complementary Reimagined shader. I made a demonstration in the Video and would appreciate any help with this.

https://github.com/The-Nexus-Project/Limitless-6/assets/84398631/616f208c-74bb-4c87-aba1-78d20363f85c

### Pack Version

Version: 1.28.1

### To Reproduce

1. Check fps without F1 or debug screen enabled
2. Enable F1 or debug screen and check fps

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [X] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

My system specs:
OS: Windows 10 pro
cpu: Ryzen 7 5800x
gpu: RX 6800 XT
ram: 32gb 3200mhz (10048mb allocated to minecraft)
AMD Software: PRO edition 23.Q1.1

**Comment by Gbergz** [comment]
Responded in discord. Closing here.
