### ISSUE TITLE
[Issue]: Screenshot Viewer

### ISSUE THREAD

**Issue by CamaroKing59** [The-Nexus-Project/Limitless-6#113]
### What happened?

Seems like Screenshot viewer is causing the server to not start.. I disabled it on the server and it turned on.. Not sure if its a client side mod or not

### Pack Version

Version: 1.29.0

### To Reproduce

1.Install Latest version 1.29.0 of Limitless 6

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
https://pastebin.com/w5VgUsSS
```

### Anything else to add?

No

**Comment by Gbergz** [comment]
Well if you have Screenshot Viewer in your server, that's not a pack problem, nor is it on us.

**Comment by Gbergz** [comment]
That mod isn't in the server files if you use the official server files.
v1.29.0: https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-6/files/4626117

**Comment by CamaroKing59** [comment]
I installed it via Bisect hosting so maybe they messed up the files when they uploaded them for pre install I dk

**Comment by Gbergz** [comment]
Can you open up a ticket with them and tell them their install for Limitless 7 is messed up?

**Comment by Gbergz** [comment]
Never mind seems they've already posted an hotfix for their server install.

**Comment by Gbergz** [comment]
Fixed.

**Comment by CamaroKing59** [comment]
awesome I did know for sure if it was on their end or yours thats why I put in a report about it XD
