### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by svg-rs** [The-Nexus-Project/Limitless-6#114]
### What happened?

Can't see my hands, other people or other mobs. Bug only started happening after restarting the server with stop.

### Pack Version

Version: Latest

### To Reproduce

1. Have a large area of mobs around you
2. Restart server with "stop" command
3. Load back in

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [x] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

### Anything else to add?

[latest.log](https://github.com/The-Nexus-Project/Limitless-6/files/12021999/latest.log)

**Comment by Gbergz** [comment]
Restart your game once or twice, this is a very very very rare issue.
