### ISSUE TITLE
[Issue]: 集成动力有些物品在多人游戏中不起作用

### ISSUE THREAD

**Issue by 821399289** [The-Nexus-Project/Limitless-6#115]
### What happened?

A bug happened!

### Pack Version

Version: 1.29.0

### To Reproduce

最近在游玩中发现集成动力（玩家模拟器、方块破坏口）在多人游戏中没有效果。单人游戏可以正常使用

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
English.
