### ISSUE TITLE
[Issue]: No way to automate Resonating Ore

### ISSUE THREAD

**Issue by nddragoon** [The-Nexus-Project/Limitless-6#119]
### What happened?

Resonating Ore from Deep Resonance isn't obtainable in any way other than mining it in the overworld (i haven't found any in the end, there might be some in the nether, there isn't any in the mining dimension either)

### Pack Version

Version: 1.30

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

Deep Resonance isn't particularly well maintained or documented, but you need a decent amount of resonating ore steadily coming in to keep producing crystals, and not being able to get it from any void miners or even the mining dimension makes the mod basically unusable in practice.

**Comment by Gbergz** [comment]
This isn't a pack issue, but in the future it will be in the Mining Dimension.
