### ISSUE TITLE
[Issue]: Error occurred during initialization of boot layer java.lang.module.FindException: Error reading module: libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 60.0

### ISSUE THREAD

**Issue by cl500** [The-Nexus-Project/Limitless-6#13]
### What happened?

Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 60.0

### Pack Version

Version: 1.3.4

### To Reproduce

tried to run the server

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 60.0
```

**Comment by Gbergz** [comment]
Not a modpack issue. Re-install java, Re-install modpack. Re-install mc files.
