### ISSUE TITLE
[Issue]: Unable to download required mods using ATLauncher

### ISSUE THREAD

**Issue by Arkandos** [The-Nexus-Project/Limitless-6#139]
### What happened?

Shiftedlib 1.0.2 and witherproofed 2.7.4 are unable to be downloaded since those versions are no longer available.
It still works on the curselauncher, I don't know why. Maybe they keep the files even if they are unlisted on the public mod websites.

### Pack Version

Version: 1.37.0

### To Reproduce

Install pack using 3rd party launcher like ATLauncher

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
This is not a pack issue.
Edit: The dev deleted those versions specifically. And because of that they cant be downloaded. Pack still works without them and they are not needed, so they can be skipped.

A future pack update will fix this. No ETA.
