### ISSUE TITLE
"Not a modpack issue. Re-install java, Re-install modpack. Re-install mc files."

### ISSUE THREAD

**Issue by cl500** [The-Nexus-Project/Limitless-6#14]
Reinstalled everything. Still same error. Ubuntu 20.04. openjdk version "11.0.16". maybe you could help me more instead of closing everytime after one sentence

**Comment by Gbergz** [comment]
https://discord.gg/gwzpyQb

**Comment by Gbergz** [comment]
It's not a modpack issue, and I know nothing about ubuntu, but maybe someone in the discord can help. Sorry.
