### ISSUE TITLE
[Issue]: My game Crash

### ISSUE THREAD

**Issue by Kaufhalle** [The-Nexus-Project/Limitless-6#16]
### What happened?

Idk what is the issue here but i think you can help me

### Pack Version

Version: Limitless-6-1.4.0

### To Reproduce

1.i start the game and its crash 

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
https://pastebin.com/0uJ2rdFf
this is the Log.txt Idk where is the probleme here
```

**Comment by ReaperMilk11** [comment]
when i try to create world it stops at 1% then crash
