### ISSUE TITLE
[Issue]: placing elementalcraft extractor causes game crash

### ISSUE THREAD

**Issue by Egamus30** [The-Nexus-Project/Limitless-6#20]
### What happened?

A bug happened! Placed an extractor from Elementalcraft mod and got a game crash.

### Pack Version

Version: Tnp limitless 6  v1.5.0

### To Reproduce

1.place small element container
2. place a element extractor on top

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
https://bytebin.lucko.me/krN6Ra2cIR
```

### Anything else to add?

only crashes for me not for other players on server.

**Comment by BlueGodBalmung** [comment]
Same here, disabling "out of sight" mod stopped the crashing for me.

**Comment by Gbergz** [comment]
Fixed awhile back.
