### ISSUE TITLE
Enchanting Infuser not allowing for more than 15 bookshelf levels.

### ISSUE THREAD

**Issue by xsaber125** [The-Nexus-Project/Limitless-6#21]
set up the enchanting infuser the correct way. something in the modpack is limiting the amount bookshelves increase the enchanting level by. 
![unnam2(1)](https://user-images.githubusercontent.com/42988540/204624551-acfb70e6-c93f-4ab7-9856-4471e7425e58.jpg)
![unnamed](https://user-images.githubusercontent.com/42988540/204624555-66be26e1-3bcd-4acf-ac45-30b4d628c22a.jpg)
ive looked through configs as i have it set up on my server. i cant find which one is affecting the advanced infuser.

**Comment by Gbergz** [comment]
You need Apotheosis Shelves.

**Comment by xsaber125** [comment]
> 

i would love if you could show me these bookshelves your talking about. i have gone on there modpage for the enchanting infuser mod. there page literally says to use the base bookshelf.. ive gone into the creative menu no section for the mod, and not a single bookshelf by the mod. and jei only brings up the enchanting infuser and the advanced version when searching by mod. so either im missing something here or theres a mod conflict that hopefully can be figured out. i check apotheosis as well since i know it heavily messes with enchanting but it literally is compatible with enchanting infusers, as well as not a single thing in the configs referencing a change to bookshelves. and enchanting infusers configs dont even cover the bookshelves. your help in resolving this matter would be greatly appreciated as i along wiht my players were looking forward to using this mod:)

**Comment by xsaber125** [comment]
> You need Apotheosis Shelves.

thank you, somehow they didnt pop up at all when i typed in shelves trying to find some that went over 15
