### ISSUE TITLE
[Issue]: Refined Storage and JEI FPS drop

### ISSUE THREAD

**Issue by iKraulas** [The-Nexus-Project/Limitless-6#22]
### What happened?

When you open item crafting possibility via RS grid FPS drops to zero or starts really fps lagging. 
The problem depends on the opened item page. and if there is an item with multi-choice or material to use. more things you can use for that item, the stronger the lag spike is.

### Pack Version

Version: 1.6.0

### To Reproduce

1. Simple open what you can make out of White glazed terracotta.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by CrimsonXMC** [comment]
Yeah, this is a frequent problem. It seems to mostly happen with things with multiple variants. Logs, Planks, Terracotta.
