### ISSUE TITLE
[Issue]: Spatial Comb quest gives non-existing item as reward

### ISSUE THREAD

**Issue by Flachdachs** [The-Nexus-Project/Limitless-6#26]
### What happened?

Because AE2 changed the way how to obtain Certus Quartz Crystals the quest Spatial Comb in the Productive Bees page needs an update. Currently Certus Crystal Seed is part of the reward, but this doesn't exist anymore.

### Pack Version

Version: 1.7.0

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
I'll solve it for a future update. Thanks for report.
