### ISSUE TITLE
cant enchant annihilation plane with silk

### ISSUE THREAD

**Issue by Galygious** [The-Nexus-Project/Limitless-6#27]
What happened?
only options for enchant are xp boost, miner's fervor, tombstone soulbound, and reactive. even using an avil.

Pack Version
Version: 6-1.8.0

To Reproduce
No response

Are you using OptiFine, Rubidium, or Oculus?
 No. None of them. Unmodified.

Are you on a Server?
 Yes.

Relevant log output / crash report.
No response

Anything else to add?
this sucks cause automated ae2 crystal growth is made much harder by this change

**Comment by Galygious** [comment]
though it does show as a possible enchant on the usage menu

**Comment by Gbergz** [comment]
Sorry I am not in-game, what's the `annihilation plane`? and `silk`?

**Comment by Galygious** [comment]
annihilation plane is a block breaker from the ae2 mod. silk is the silk touch enchantment which makes it so blocks are mined as their own block and not their result. so stone from stone instead of cobblestone
