### ISSUE TITLE
[Issue]: crash on the 2 new updates for me

### ISSUE THREAD

**Issue by Dablackmamba08** [The-Nexus-Project/Limitless-6#29]
### What happened?

crash when trying to enter world

https://controlc.com/1c3a5d8c

### Pack Version

Version: 1.8.0 and 1.9.0

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [x] No.

### Relevant log output / crash report.

```shell
https://controlc.com/1c3a5d8c
```

**Comment by Gbergz** [comment]
You forgot to fill out the checkmarks. Etc.

Anyway,
Try reinstalling a fresh instance using the ATLauncher. 

https://atlauncher.com/downloads
