### ISSUE TITLE
[Issue]: missing item   ars_nouveau:arcane_stone

### ISSUE THREAD

**Issue by AWDoBaun** [The-Nexus-Project/Limitless-6#32]
### What happened?

Got 8 items that ftbquests tried to create that are described as "ars_nouveau:arcane_stone" from "Enchanting Apparatus" quest on "Ars Nouveau" page.

Likely should be "ars_nouveau:sourcestone".

### Pack Version

Encountered in Version:  1.9.1

Looks like quest is still encoded with the missing item after updating to 1.10.0

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Already reported in our discord so I will close this, but thanks for report! :)
This will be sorted in a new update.
