### ISSUE TITLE
[Issue]: Crash for New AMD Driver 22.6.1 and highly. Rx480

### ISSUE THREAD

**Issue by KozhaBog** [The-Nexus-Project/Limitless-6#34]
### What happened?

Install new Driver increase FPS before ~200FPS. But Rundom crash videocards drivers (not crash java or minecraft)
If you stand at one point, you don’t fly out, you can even walk silently (I set up an hour at the base, went to the village and immediately flew out).
On amd driver 22.5.1 the game doesn't crash. But fps with rubidium 20-30
Setup:
RX480
Ryzen 5-2600
64GB RAM
m2 Evo 980

### Pack Version

Version: TNP 6 1.10

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
I can't do anything about AMD drivers, sorry.

Roll back and stay on that one that worked better.

**Comment by Gbergz** [comment]
But. Try this:

modpack\config\flywheel-client.toml

turn
backend = "INSTANCING" to "OFF".

If it doesn't work. Sorry no clue.

**Comment by KozhaBog** [comment]
> But. Try this:
> 
> modpack\config\flywheel-client.toml
> 
> turn backend = "INSTANCING" to "OFF".
> 
> If it doesn't work. Sorry no clue.

Thank you a thousand times.That helped. 
Now with 200 fps without shaders and 50-70 with them.
Somewhere I read this *flywheel* in the bugreport of your discord server. I thought it was something on *create*, but I still don't use it

**Comment by Gbergz** [comment]
Sweet! Glad it worked :)
