### ISSUE TITLE
[Issue]: Crash a minute or less after loading into a new world 

### ISSUE THREAD

**Issue by Bosman9000** [The-Nexus-Project/Limitless-6#35]
### What happened?

I created a new world and it crashes sometime a few minutes later or a few seconds later.

### Pack Version

Version: TMP Limitless 6 1.10.0

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

[hs_err_pid13816.log](https://github.com/The-Nexus-Project/Limitless-6/files/10368588/hs_err_pid13816.log)

**Comment by Gbergz** [comment]
Try this:

modpack\config\flywheel-client.toml

turn
backend = "INSTANCING" to "OFF".

If it doesn't work. Sorry no clue.

**Comment by Bosman9000** [comment]
Yeah I checked that before and its already set to off.
