### ISSUE TITLE
[Issue]: No Drops

### ISSUE THREAD

**Issue by BarterChain65YT** [The-Nexus-Project/Limitless-6#38]
### What happened?

A bug happened! I'm unable to get blaze rods when killing a blaze, Wither Skeletons and Phantoms Drop Nothing (now finding out no hostile mod drops anything for me for some reason)

### Pack Version

Version: 1.11.0

### To Reproduce

1.Kill any Hostile Mob

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
By default I can't reproduce this issue. Pretty sure you have something equipped that makes this happen for you.

**Comment by BarterChain65YT** [comment]
how do i know what causes it though
