### ISSUE TITLE
[Issue]: No options for single player or or multiplayer in menu

### ISSUE THREAD

**Issue by EBRPyle** [The-Nexus-Project/Limitless-6#39]
### What happened?

Loded game and in main screen theres no button to actually play the game

### Pack Version

Version: 

### To Reproduce

1.Start game, see glitched menu

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Uhh, what. 🤔 
I would reinstall, this sounds like a corrupt install or similar.

**Comment by EBRPyle** [comment]
I figured it out, for some reason it opened in demo mode, didnt know there was such a thing. Appearantly I was logged into the wrong Microsoft account without realising there was a wrong one
    On Tuesday, January 17, 2023 at 02:52:46 PM CST, Gbergz ***@***.***> wrote:  
 
 


Uhh, what. 🤔
I would reinstall, this sounds like a corrupt install or similar.

**Comment by Gbergz** [comment]
Heh, never heard of that one before. glad it's solved. 👍
