### ISSUE TITLE
[Issue]: Refined Storage Silicon is impossible to obtain

### ISSUE THREAD

**Issue by WiseHorror** [The-Nexus-Project/Limitless-6#4]
### What happened?

Refined Storage silicon has no recipe and using AE2 Silicon for recipes doesn't work

### Pack Version

Version: 1.0.0

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Intended.
Use Silicon from AE2.

**Comment by Gbergz** [comment]
Oversight on my part, it is actually uncraftable. Will get this sorted.
Thanks for noticing!

**Comment by Gbergz** [comment]
Fixed in v1.1.0
