### ISSUE TITLE
Cant start the pack

### ISSUE THREAD

**Issue by aillariz** [The-Nexus-Project/Limitless-6#41]
### What happened?

If i start the pack it load until second phase than it crash and say game crashed (failed to create model for minecraft:tropical_fish)
but the mob switches sometimes to cod or other fishes

### Pack Version

Version: 1.12.0

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

### Anything else to add?

![bug_](https://user-images.githubusercontent.com/123276062/213891011-ddb84597-d526-40de-b257-9248342049dc.PNG)

**Comment by aillariz** [comment]
(i wrote the last report but nothing helped i use java 17.04.1 and i set flywheel to OFF) and im using windows i tried in curse atl and multiMC

**Comment by Gbergz** [comment]
Try removing the mod Nicephore see if it launches

**Comment by aillariz** [comment]
thanks Nicephore was the problem
