### ISSUE TITLE
[Issue]: Impossible to get max level enchants

### ISSUE THREAD

**Issue by Nideau** [The-Nexus-Project/Limitless-6#42]
### What happened?

Hi, I don't know if it's intended or if something has changed in Apotheosis but I can't get the enchants with maximum levels with librarian trades or by combining then in an anvil.

ex: Fortune max lvl is VIII, thru trades I only manage to get Fortune III max and i can't combine them in an anvil.

### Pack Version

Version:  6-1.12.0

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Quark Tomes are your answer, or use the enchanting infuser.
