### ISSUE TITLE
[Issue]: No Osmium in Mining Dimension

### ISSUE THREAD

**Issue by bobzilla69** [The-Nexus-Project/Limitless-6#44]
### What happened?

Hi,

I have been mining the the mining dimension but have yet to find any Osmium ore, to check this I used a scanner with Osmium blocks (normal and deepslate) I found in the overworld and I cant see anything, I have gone out 8000 blocks and yet to see a single ore.

I have found other ore from Mekanism but seems to be Osmium that is missing

### Pack Version

Version: 1.13.2

### To Reproduce

use scanner in mining dimension (Just Another Mining Dimension) to scan for osmium ore

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
N/A
```

### Anything else to add?

N/A

**Comment by Gbergz** [comment]
This is known. For now it has no osmium. Or some other ores aswell. Not sure if I can fix this.
Sorry for the inconvenience.
