### ISSUE TITLE
[Issue]: Alex Mobs dont spawn

### ISSUE THREAD

**Issue by JWTHDYTWA** [The-Nexus-Project/Limitless-6#45]
### What happened?

Almost none of Alex's Mobs mobs spawn naturally.

### Pack Version

Version: 1.13.1

### To Reproduce

1. Try to find any Alex's Mobs mob

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
This is intended bcs of lag and some other issues.

All loot drops from the mobs have been added to loot table, chests around the world. 

You can however turn them back on if you want, delete the alexsmobs config file and the folder. And restart the game/server.

**Comment by JWTHDYTWA** [comment]
You can at least re-enable farseer because it has very specific spawn conditions.

**Comment by Gbergz** [comment]
I'll look into enabling the farseer!
