### ISSUE TITLE
[Issue]: Witherproofed mob drops are broken

### ISSUE THREAD

**Issue by JWTHDYTWA** [The-Nexus-Project/Limitless-6#46]
### What happened?

Items from **Witherproofed** mod which are supposed to be mob drops are unobtainable, making the whole mod useless.

- Withered Powder
- Ghostly Essence

### Pack Version

Version: 1.13.1

### To Reproduce

1. Try to obtain any item from Witherproofed

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
These are turned off because they interfere with vanilla loot tables. But I will add recipes for these two instead next update.

**Comment by Gbergz** [comment]
I think I've found a way to re-introduce their drops into the loot tables. Fixed in next update (v1.14.)
