### ISSUE TITLE
[Issue]: Unable to find creeper seeds from Pneumatic Craft

### ISSUE THREAD

**Issue by IgnisAstra** [The-Nexus-Project/Limitless-6#47]
### What happened?

I am using TNP Limitless 6 as a modpack for a server i'm on. Creeper seeds do not show up on JEI unless it's from Mystical Agriculture, yet there are supposed to be seeds dropping from Creeper added by PneumaticCraft, I already looked through the configs and couldn't find anything about the seeds. Unknown with what to do.

### Pack Version

Version: 1.12.0

### To Reproduce

1. Kill a creeper without it exploding
2. Can't find the seed from pneumatic craft in JEI

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [X] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Already in discord, no need to open here.
