### ISSUE TITLE
[Issue]: No "+" icon to use

### ISSUE THREAD

**Issue by ilibuu** [The-Nexus-Project/Limitless-6#48]
### What happened?

There is no Icon "+" in the crafting menu

### Pack Version

Version: v1.14.1

### To Reproduce

1. just go in the crafting table and go on any recipe

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
> There is no Icon "+" in the crafting menu

I don't understand

**Comment by ilibuu** [comment]
![2023-02-06_20 20 26](https://user-images.githubusercontent.com/124624246/217064964-7e487410-bc5c-4da9-a178-7fb88ef18f7e.png)
At first, there is no Crafting Table Recipe for the Bookshelf for example.
2. In this Recipie is no + button for the crafting table

**Comment by ilibuu** [comment]
The crafting table above is not for a single recipe

**Comment by Gbergz** [comment]
Reinstall the modpack fresh.
I see you're on 1.14.1, but it was fixed in that update. Probably didn't get installed correctly.

**Comment by ilibuu** [comment]
okay, so what i have to do now?

**Comment by ilibuu** [comment]
okay, thank you

**Comment by DreamingLamb** [comment]
Might be worth loading a single player world and then logging back into the server too?  I've seen JEI not display recipes, possibly due to a caching bug.  Good chance I'm wrong though :)

**Comment by Gbergz** [comment]
this is an issue fixed in an update or two ago, now.
