### ISSUE TITLE
[Issue]: Shulker Shells won't stack with Apotheosis Affixes

### ISSUE THREAD

**Issue by DreamingLamb** [The-Nexus-Project/Limitless-6#49]
### What happened?

A mod (I'm not sure which, maybe Quark) changes Shulker Shells to be able to be used as a helmet, with this, Apotheosis then adds affixes to them when dropped by killing a Shulker.  While this could be useful, it also mean that Shulker Shells with affixes are non-stackable.

### Pack Version

Version: 1.13.2

### To Reproduce

1. Kill a bunch of Shulkers
2. Witness the loss of inventory space

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
N/A
```

### Anything else to add?

Fix:

Update '..\config\apotheosis\adventure.cfg' from line:38

    # A list of type overrides for the affix loot system.  Format is <itemname>|chance|<type>.  Types are SWORD, TRIDENT, SHIELD, HEAVY_WEAPON, BREAKER, CROSSBOW, BOW [default: [minecraft:iron_sword|SWORD]]
    S:"Equipment Type Overrides" <
        minecraft:iron_sword|SWORD
        minecraft:shulker_shell|NONE
     >

**Comment by Gbergz** [comment]
Fixing for next update. 👍
