### ISSUE TITLE
Follow up for Starlight

### ISSUE THREAD

**Issue by DraTrav** [The-Nexus-Project/Limitless-6#50]
<img width="410" alt="Screenshot 2023-02-18 172651" src="https://user-images.githubusercontent.com/42803478/219904085-2e768f59-0bdb-4ca8-a823-1503a1f0d485.png">
I'm just following up, I noticed crashes and weird performance issues on the client with starlight, However on the server side of things there are some major improvements to tps and mspt. My mspt before was 1500 and after was 300. I can get screenshots from spark if requested 

I would recommend it for server side only.

**Comment by Gbergz** [comment]
So, no crashes because of Starlight on the server?
Did you keep Canary, or did you remove it in favor of starlight?

**Comment by DraTrav** [comment]
They are compatible, I kept Canary and still saw massive improvement.

**Comment by Gbergz** [comment]
Did you add Starlight to an existing world? I am unsure whether this will cause unintended side effects if added to an existing. But I could be wrong.

**Comment by Gbergz** [comment]
I do want to test this on our official servers before adding it to the official server file pack. But not sure if it'll break it or not. 🤔

**Comment by DraTrav** [comment]
I did add it to an existing world, no negative side affects that I am aware of. It just affects the lighting engine. The worst it can do is cause bugs related to that, but I have not expericed any.

**Comment by Gbergz** [comment]
Alright, thank you for testing! I saw you said it was a huge improvement. To what parts exactly?

**Comment by DraTrav** [comment]
Overall tps and mspt, I did also notice already loaded chunks loading quicker and anything that gives off light having less of an effect on tps. For example, in my world I use glass domes a lot in building and because of how minecraft handles lighting it can actually cause some interesting "skips" whenever I teleport back. Starlight completely removed those skips. Its was also noticable with large amount of ice generating due to roller skates and frost walker. But starlight helped with the effect it had tremendously.

**Comment by Gbergz** [comment]
Interesting and good news then, I shall try it on the official servers soon, see what effect it gives.

**Comment by DraTrav** [comment]
Both of these were tested after about 10 mins of my server starting. They are 

This is before starlight 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/42803478/220633748-f2e56056-7dde-4143-8671-7d70ab79ee0b.png">

https://spark.lucko.me/4Few2t3JnY

This is after

<img width="301" alt="image" src="https://user-images.githubusercontent.com/42803478/220634065-3aafc29b-b792-4384-8363-4bbe85a52123.png">

https://spark.lucko.me/3o3L0E6RQp

**Comment by Gbergz** [comment]
Currently been testing on the Official Servers for about 5 hours, so far so good. 👍

**Comment by Gbergz** [comment]
Closing as I added this awhile back for Server Files only.
