### ISSUE TITLE
[Issue]: Out of Sight causes crash with ElementalCraft

### ISSUE THREAD

**Issue by nddragoon** [The-Nexus-Project/Limitless-6#53]
### What happened?

My game crashed upon placing an Element Extractor from ElementalCraft. Removing Out of Sight fixed it.

### Pack Version

Version: 1.15

### To Reproduce

1. Find an ElementalCraft element source
2. Place a small element container under it
3. Place an element extractor on the container

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
https://pastebin.com/j4SDDMVW
```

**Comment by Gbergz** [comment]
This is known and reported, but thanks for bringing it up again though!
