### ISSUE TITLE
Limitless-6 Crash on Start 

### ISSUE THREAD

**Issue by MagnetarOps** [The-Nexus-Project/Limitless-6#54]
What happened?
A bug happened!

Pack Version
Version: 1.19.2

To Reproduce
1.press play, crashes almost immediately

(pushed ram to 12GB)

Are you using OptiFine, Rubidium, or Oculus?

 No. None of them. Unmodified.
Are you on a Server?
 No.

Relevant log output / crash report.

  <log4j:Event logger="Quartz/OpenGLSelector" timestamp="1677184360991" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Quartz OpenGL version search enabled, this may potentially cause issues with some graphics cards, please report issues]]></log4j:Message>
  </log4j:Event>

  <log4j:Event logger="Quartz/OpenGLSelector" timestamp="1677184360991" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Searching for latest OpenGL version]]></log4j:Message>
  </log4j:Event>

<log4j:Event logger="Quartz/OpenGLSelector" timestamp="1677184360993" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Attempting version 4.6 ]]></log4j:Message>
  </log4j:Event>

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f7be2c1f290, pid=26677, tid=26678

 JRE version: OpenJDK Runtime Environment Temurin-17.0.1+12 (17.0.1+12) (build 17.0.1+12)
 Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (17.0.1+12, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 C  [libglfw.so+0x1f290]

 Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/User/.config/gdlauncher_next/instances/TNP Limitless 6   LL6/core.26677)

An error report file with more information is saved as:
 /home/User/.config/gdlauncher_next/instances/TNP Limitless 6   LL6/hs_err_pid26677.log

Anything else to add?
Used GDLauncher Flatpak and Github Version
Java Version Used was the standard installed by GDLauncher
Seems like an OpenGL related Error.
I'm using Manjaro (Arch based Linux Distro) as an Operating System
The grafikcard used is an Nvidia Intel combination

**Comment by zanaran** [comment]
I'm getting this also. I've been using Arch. I've also used the FTB App and Prism Launcher to launch the game. On a fresh install of Arch, I can get Prism Launcher to run the game 1 time with no problems. After I close the game and restart then it always crashes with this same error. 
[minecraft log.txt](https://github.com/The-Nexus-Project/Limitless-6/files/10938194/minecraft.log.txt)
![Screenshot_Console window for TNP Limitless 6 - LL6_2](https://user-images.githubusercontent.com/14294353/224215973-9be2a270-a72a-4a84-ad55-413b55228769.png)

**Comment by Gbergz** [comment]
Crashes on OS's other than Windows are known. 
There's a long thread about it in our Discord. Check it out: https://discord.gg/gwzpyQb

Then when joined click: https://discord.com/channels/525232025355943956/1051185839822077992
