### ISSUE TITLE
[Issue]: 99% Usage on both gpu and cpu 

### ISSUE THREAD

**Issue by ActuallyStephen** [The-Nexus-Project/Limitless-6#56]
### What happened?

The modpack pretty much floors my usage on gpu and cpu im running a radeon rx580 series, with 16gb of ram 5-7 running the pack a Ryzen 5 2600 6 core. its pretty much stutters all the entire pack loading process then crashes when trying to create a world or join a server. 

### Pack Version

Version: 1.16.0

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

Im not sure if my system just cant run it or what any info would help thank you. The pack looks amazing I would love to play.

**Comment by wendylady** [comment]
Post to add that I have a very similar setup and issue.   I have the pack set at 10g with Most of the stuff set to normal graphics with fewer effects.  It still has the starting issues and takes all the GUP/CPU but then at least with 10 to 12 g set it loads. Then when in the game will run ok. Not the best way to fix it but it gets me playing.

 ( mine Ryzen 5 3600 6-Core Processor 3.59 GHz 16g, ) I

**Comment by ActuallyStephen** [comment]
Hey

**Comment by ActuallyStephen** [comment]
Hey Wendy, I kind of fixed it by uninstalling my version of java and reinstalling the latest version i know it seems like a too easy to be solution but it did work for me. Hope this helps have fun its a wonderful pack!
