### ISSUE TITLE
[Issue]: NO BOAT :(

### ISSUE THREAD

**Issue by KhawknBawls** [The-Nexus-Project/Limitless-6#58]
### What happened?

when boat go on da water the server go uh oh and splat

### Pack Version

Version: 1.17.0

### To Reproduce

1. host server
2. join server
3. make big boat
4. place boat in water
5. server go uh oh

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
fixed in newer updates
