### ISSUE TITLE
[Issue]: sorting in backpacks not working when adding the stacking addon

### ISSUE THREAD

**Issue by DiehardRuby** [The-Nexus-Project/Limitless-6#6]
### What happened?

playing limitless6 just wondering and one else getting java.lang.illegalStateExcpetion: unequal before and after item counts, when using the sophistical backpack with the stacking addon im trying to sort the backback and it wont work any suggestons

### Pack Version

Version: 1.19

### To Reproduce

1. get backpack
2. get addon stack upgrader
3. add to backpack with ore items that can stack
4. try to sort inventory 
5. java.lang.illegalStateExcpetion: unequal before and after item counts will show up when trying to sort with minerals 

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
I meant the Sophisticated Backpacks issue tracker when I said report it to them 😅
