### ISSUE TITLE
Discord invite doesnt work

### ISSUE THREAD

**Issue by krustymk** [The-Nexus-Project/Limitless-6#60]

**Comment by Gbergz** [comment]
Yes it does, just tested it.

**Comment by krustymk** [comment]
So did i, do i need to screenshot?

**Comment by krustymk** [comment]
![Discord](https://user-images.githubusercontent.com/5390088/224819253-c621a345-7b59-402d-aa40-ac4cf13a59ac.jpg)

From the bottom of the Curseforge page

**Comment by krustymk** [comment]
Works if im logged into Discord, maybe a discord thing then just never seen it before
