### ISSUE TITLE
[Issue]: Looking at a block gen pedestal causing crashes

### ISSUE THREAD

**Issue by KP-Names** [The-Nexus-Project/Limitless-6#62]
### What happened?

I have a pedestal generating sand, and when I started using it, it was fine, but after I left it to run for a while, I found any time my pointer passed over it, it would crash my game. I know it was the pedestal because after I carefully encased it in stone so I couldn't view it as a player, it wasn't crashing anymore. The only thing of note that I run differently than the base game is having the Ars Nuevo dynamic lighting on.

### Pack Version

Version: 1.17

### To Reproduce

1. Allow a pedestal with a block generating upgrade to fully fill
2. Turn to stare directly at the pedestal 
3. Crash

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

I suspect there might be a bad interaction between a full inventory pedestal and whichever mod is being used to describe the objects and machines you're looking at. I didn't get a chance to test it with that disabled, but it may be a good place to start.
[crash-2023-03-17_19.00.55-server.txt](https://github.com/The-Nexus-Project/Limitless-6/files/11035074/crash-2023-03-17_19.00.55-server.txt)
[2023-03-17-2.log](https://github.com/The-Nexus-Project/Limitless-6/files/11035094/2023-03-17-2.log)

**Comment by KP-Names** [comment]
Updated my post with the documents attached. Hope that helps!

**Comment by KP-Names** [comment]
Mod creator let me know it should be resolved in v0.2.39+

**Comment by Gbergz** [comment]
Great! Thanks for the update.
