### ISSUE TITLE
[Issue]: Trojan inside your Server files ? 

### ISSUE THREAD

**Issue by LovenKyuu** [The-Nexus-Project/Limitless-6#65]
### What happened?

I want to install the new version of TNP6, 1.19 server files but when i try to open the zip file. Windows Defender detect a Trojan inside. 

![ApplicationFrameHost_Oz66TshHv4](https://user-images.githubusercontent.com/117116512/227767781-11d70af4-7741-4c4a-84fb-d81e39953cb4.jpg)

### Pack Version

Version: 1.19

### To Reproduce

1. Download Server File with Curseforge or until ur direct link 
2. Try to start
3. Antivirus block 

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
There is no such thing in the server files. If it shows that it's a false positive.
