### ISSUE TITLE
[Issue]: i kwwp crashing on the server

### ISSUE THREAD

**Issue by Evilteen18** [The-Nexus-Project/Limitless-6#66]
### What happened?

A bug happened! my waystone had home on there and i click it not thinking about where it gone and i crash now NA server
[crash-2023-03-22_14.08.33-server.txt](https://github.com/The-Nexus-Project/Limitless-6/files/11073147/crash-2023-03-22_14.08.33-server.txt)

### Pack Version

Version: the new one

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [x] Yes.
- [ ] No.

### Anything else to add?

if you can try to save my inventory

**Comment by Gbergz** [comment]
> ServerHangWatchdog detected that a single server tick took 60.00 seconds

Your server.properties & override.properties files are invalid, you need the ones from the server files.

**Comment by Evilteen18** [comment]
ok what about this one im on your NA server 
[2023-03-26-4.log](https://github.com/The-Nexus-Project/Limitless-6/files/11073303/2023-03-26-4.log)

**Comment by Gbergz** [comment]
Official Server issues goes into the discord under category "server-discussions".
Invite link: https://discord.gg/gwzpyQb
