### ISSUE TITLE
Game Crashes after placer an item collector from the items collector mod

### ISSUE THREAD

**Issue by hyperdensemediasign** [The-Nexus-Project/Limitless-6#68]
you cant load into the world once the item is placed. 

[crash-2023-03-27_20.52.51-client.txt](https://github.com/The-Nexus-Project/Limitless-6/files/11082171/crash-2023-03-27_20.52.51-client.txt)

**Comment by Gbergz** [comment]
remove out of sight, known problem. 
PS. Check past issues before posting next time aswell, could've saved you a report. :)
