### ISSUE TITLE
Shape Card dosent work (rft tools bug ?)

### ISSUE THREAD

**Issue by Sirmarvelot** [The-Nexus-Project/Limitless-6#72]
![2023-04-09_17 23 25](https://user-images.githubusercontent.com/130296256/230781581-89d8865b-7b76-484d-98d1-a595eadb4b6c.png)
![2023-04-09_17 23 36](https://user-images.githubusercontent.com/130296256/230781585-44d22fac-9093-4bb4-9bae-195d4b88a723.png)
the shape card for the builder dosent work, whatever i try there are always zero blocks is this a bug ?

**Comment by Gbergz** [comment]
replied in discord, should be fixed next update.
