### ISSUE TITLE
[Issue]: domum ornamentum Cobble Placed - transformed to Clay - On Touch Games Crash 

### ISSUE THREAD

**Issue by SamuraiEinhorn** [The-Nexus-Project/Limitless-6#73]
### What happened?

Tryed to Place Cobble Roofs from domum ornamentum with the builder tool , after first try it placed 1 Clay Roof from domum ornamentum and if il try to break it the games crashes . Now im Standing on it and the Game Crashes every time 

### Pack Version

Version: 
[crash-2023-04-11_22.07.02-client.txt](https://github.com/The-Nexus-Project/Limitless-6/files/11204736/crash-2023-04-11_22.07.02-client.txt)

Game Version is 1.19.2 

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [X] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

### Anything else to add?

Tryed to Put Rubi + Ocu out but dosnt work

**Comment by Gbergz** [comment]
Continued in discord.
