### ISSUE TITLE
Issues with right click on inventory

### ISSUE THREAD

**Issue by djdado16** [The-Nexus-Project/Limitless-6#74]
When you right click on some made recipe you get 64 items even if you dont have that much resources to make...i even get so much 64 sticks that everytime i log on on server its near workbench on floor so i can pick  it up...and i play on your orginal server eu1

**Comment by Gbergz** [comment]
I've identified the issue and will have a fix on CF soon.
Thanks for report!

**Comment by Gbergz** [comment]
Out: https://www.curseforge.com/minecraft/modpacks/tnp-limitless-6/files/4492816
