### ISSUE TITLE
[Issue]: Wooden Jetpack quest does not complete

### ISSUE THREAD

**Issue by SonicEdge** [The-Nexus-Project/Limitless-6#79]
### What happened?

Upon crafting a wooden jetpack, the quest does not complete.

### Pack Version

Version: 1.22.0

### To Reproduce

1. Complete Wood Jetpack Parts quest
2. Attempt to complete Wood Jetpack quest.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

![image](https://user-images.githubusercontent.com/59069765/234974852-9301f3a6-1092-4289-8f9e-70457bd8de74.png)
![2023-04-28_05 46 47](https://user-images.githubusercontent.com/59069765/234974889-51a979bb-0dae-43a5-9df8-e30563fd32a6.png)

**Comment by Gbergz** [comment]
Read the readme note in the chapter.
