### ISSUE TITLE
[Issue]: TNP Limitless6

### ISSUE THREAD

**Issue by 92Joanna** [The-Nexus-Project/Limitless-6#80]
### What happened?

A bug happened! καθος εγινε ενιμεροσι του modpacks δεν μου ανιγι τι να κανο βοιθιστε με

### Pack Version

Version: 1.22.0

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
English.
