### ISSUE TITLE
[Issue]: Sophisticated Backpack Bug

### ISSUE THREAD

**Issue by ThatGermanPanda** [The-Nexus-Project/Limitless-6#83]
### What happened?

When using the Backpack provided by the Starter Kit , after some time it just deletes all your Items in it

Happened to me on the Public EU1 Server
Happened to me on the Server i am now
and it happened to someone else on this Server

### Pack Version

Version: most recent 1.24.0 and the one before that

### To Reproduce

1. Use Backpack provided by the Starter Kit via Quest for a longer period of time as if you were playing normally , upgrading it etc

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Official server issues are meant to be in the discord channel, wan't to keep this out of that.
Join the discord here and discuss it in the ll6-eu1 channel under server-discussions. 

https://discord.gg/gwzpyQb
