### ISSUE TITLE
[Issue]: Duplication of items with Hexerei drying rack (come-back)

### ISSUE THREAD

**Issue by Aydenss** [The-Nexus-Project/Limitless-6#84]
### What happened?

A bug happened !

Accidental duplication with Hexerei's drying rack.
Exactly like this previously patched issue : [Issue 69](https://github.com/The-Nexus-Project/Limitless-6/issues/69)

Tried in private server as in solo with map and freshly installed modpack.

### Pack Version

Version: 1.24.0

### To Reproduce

1. Place the drying rack
2. Put any item in
3. Break the rack with the item in, and it will drop double (can use ultimine to do multiple at a time)

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Closing to not keep this visible, still open, though visible as closed. Will update here once I have more info.
