### ISSUE TITLE
[Issue]: LAN Server Error

### ISSUE THREAD

**Issue by C4rter10** [The-Nexus-Project/Limitless-6#87]
I tried joining my S/O's LAN world and i got an error saying generator galore has a version mismatch however, it displays that we both have the same version. 
![image](https://github.com/The-Nexus-Project/Limitless-6/assets/66751703/7cfad5be-57ca-4be7-86b2-09e6a66f9b42)

**Comment by C4rter10** [comment]
Oh, we also tried running a server and we get this: 
![image](https://github.com/The-Nexus-Project/Limitless-6/assets/66751703/18065aaa-3f45-48e8-b870-325ef36d1b80)

Joining the server leads to the same error as with the LAN server

**Comment by Gbergz** [comment]
your pack is corrupt
configs etc. Reinstall everything.
