### ISSUE TITLE
[Issue]: Radioactive Comb - No valid items

### ISSUE THREAD

**Issue by Flachdachs** [The-Nexus-Project/Limitless-6#88]
### What happened?

When in the quest book open the Radioactive Comb task of Productive Bees and click the comb to the left. A message "No valid items!" appears.

Additionally Powdery Comb solves the Radioactive Comb quest.

### Pack Version

Version: 1.24.0

**Comment by Gbergz** [comment]
Still will work, even if it's not clickable, like the readme note says.
It might even complete with any item due to the nbt issues.

**Comment by Gbergz** [comment]
But I will try to fix it either way for next update :)

**Comment by Flachdachs** [comment]
Another issue is in the Spatial Comb quest. It will give the old Certus Crystal Seeds as reward.

**Comment by Gbergz** [comment]
It will be fixed next update.
