### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by dvtty** [The-Nexus-Project/Limitless-6#90]
### What happened?

cant move all items with crlt + shift

### Pack Version

Version: 1.25

### To Reproduce

1.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
re-open a new issue with relevevant information. left everything blank. even title
