### ISSUE TITLE
[Issue]: Heavy stuttering

### ISSUE THREAD

**Issue by jaycee1910** [The-Nexus-Project/Limitless-6#91]
### What happened?

Heavy stuttering after playing some time. Only in the normal dimension not in the mining dimension or in nether. First few days were fine when some soft lags started to happen. It was still playable but suddenly it became way to bad. It was like 5ms freeze per second but now its like 0.1 secs freeze every half second. All computer recources are still capable of taking more load and no single cores are at 100% all the time.

### Pack Version

Version:  1.24.0 and also tested the same world on 1.26.0 with exactly the same problem.

### To Reproduce

1. It accured suddenly so the way to reproduce it is probably playing this world lol.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Sounds like you dont have enough RAM allocated, leading to stuttering when GC fills up.

**Comment by jaycee1910** [comment]
> Sounds like you dont have enough RAM allocated, leading to stuttering when GC fills up.

I have 32GB of DDR4 RAM and 12 are commited to the game.

**Comment by jaycee1910** [comment]
Small Update: tried it with 17GB allocated and a friend tried it too on single player with the same problem. I turned vsync on and got 44 FPS on average which means 1 fourth of the frames are freeze. So I consider it is an event considered lag cause it is happening every 250ms dude to the stable average FPS.

**Comment by jaycee1910** [comment]
Last Update: After some investigation on the time when the lag occured first we were able to reproduce the Block which triggered the lag. The cyclic packager costs us like 8 FPS each so something is wrong with this item. From now on the the issue is fixed and I wanted to provide you with this information if someone else gets this problem. I will write it on discord too. Have a nice day.
