### ISSUE TITLE
[Issue]: cant open the research table in Relics mod 1.19.2

### ISSUE THREAD

**Issue by Realplayer2k** [The-Nexus-Project/Limitless-6#92]
### What happened?

I can place the item on the table, but i cant open the gui with "shift+right click"

### Pack Version

Version: tnp limitless 6 1.26.0

### To Reproduce

1.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Check that you don't have anything in your off-hand, like a shield because it's invisible if not holding a weapon.

**Comment by Realplayer2k** [comment]
i cant try it, game keeps crashing without crash report (v. 1.26.0)
(the only new thing is my monitor (2560x1440 144hz)

**Comment by Gbergz** [comment]
send latest.log of when it crashes

**Comment by Realplayer2k** [comment]
[latest.log](https://github.com/The-Nexus-Project/Limitless-6/files/11643142/latest.log)

**Comment by Gbergz** [comment]
this log doesn't include a crash

**Comment by Realplayer2k** [comment]
hmm... worked on the 3rd try while i was recording...
thanks for your support :)

**Comment by Gbergz** [comment]
ah oh well, glad it works now :P
