### ISSUE TITLE
[Issue]: Scarab Talisman from Relics crashes the game

### ISSUE THREAD

**Issue by TheBananaMan99** [The-Nexus-Project/Limitless-6#93]
### What happened?

My friend somehow obtained the Talisman from a lootbag. Said item appears to crash the game

### Pack Version

Version: 1.

### To Reproduce

1.26.0

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [X] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Already known, most likely fixed next update of the modpack if the next relics update fixes it.

**Comment by Gbergz** [comment]
Send the crash report, just wanna look at it.

**Comment by Gbergz** [comment]
Just want to confirm this crash is reproducable without Oculus, can you try without it?

**Comment by Gbergz** [comment]
This will be fixed next update if Relics fixes it.
Will blacklist it from Loot Bundles either way.
