### ISSUE TITLE
[Issue]:  Loot Bundle Item Causing Disconnect

### ISSUE THREAD

**Issue by sercasm** [The-Nexus-Project/Limitless-6#94]
### What happened?

Received an item, from a lootbag, with the name "item.relics.scarab_talisman" that instantly disconnects the player on our server.  Haven't tested a singleplayer world. 
![image](https://github.com/The-Nexus-Project/Limitless-6/assets/71906775/8a5ef21b-9b8e-4943-9212-a84803a4c5f5)

### Pack Version

Version: 1.26.0

### To Reproduce

Random item drop from a lootbag.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [X] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Duplicate https://github.com/The-Nexus-Project/Limitless-6/issues/93
