### ISSUE TITLE
[Issue]: Repairing silent gear pickaxe in inventory removes enchants

### ISSUE THREAD

**Issue by Kn0wnG1itch** [The-Nexus-Project/Limitless-6#96]
### What happened?

When repairing a rose quartz pickaxe from @Silent_Gear (presumably other types as well) the enchants are removed from the pickaxe. The method of repairing that causes the issue is when you repair the item in your inventory, and silent gear allows other materials of the same tier to repair the item. Such as black diamonds combined with a rose quartz pickaxe, repairs it but also removes enchants.

### Pack Version

Version: 1.26.0

### To Reproduce

1.Repair a damaged silent gear pickaxe in the player crafting table. 

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [X] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Not an issue, this is intended.
